<?php

return [
    [
        'name' => 'appid',
        'title' => '应用AppID',
        'type' => 'string',
        'content' => [],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'appkey',
        'title' => '应用AppKEY',
        'type' => 'string',
        'content' => [],
        'value' => '2',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'voiceAppid',
        'title' => '语音短信AppID',
        'type' => 'string',
        'content' => [],
        'value' => '3',
        'rule' => 'required',
        'msg' => '使用语音短信必须设置',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'voiceAppkey',
        'title' => '语音短信AppKEY',
        'type' => 'string',
        'content' => [],
        'value' => '4',
        'rule' => 'required',
        'msg' => '使用语音短信必须设置',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sign',
        'title' => '签名',
        'type' => 'string',
        'content' => [],
        'value' => 'your sign',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'isVoice',
        'title' => '是否使用语音短信',
        'type' => 'radio',
        'content' => [
            '否',
            '是',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'isTemplateSender',
        'title' => '是否使用短信模板发送',
        'type' => 'radio',
        'content' => [
            '否',
            '是',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'template',
        'title' => '短信模板',
        'type' => 'array',
        'content' => [],
        'value' => [
            'register' => '1',
            'resetpwd' => '1',
            'changepwd' => '1',
            'changemobile' => '1',
            'profile' => '1',
            'notice' => '1',
            'mobilelogin' => '1',
            'bind' => '1',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'voiceTemplate',
        'title' => '语音短信模板',
        'type' => 'array',
        'content' => [],
        'value' => [
            'register' => '',
            'resetpwd' => '',
            'changepwd' => '',
            'changemobile' => '',
            'profile' => '',
            'notice' => '',
            'mobilelogin' => '',
            'bind' => '',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
